credentials:
  usernames:
    sprueba:
      email: streamlit11@gmail.com
      failed_login_attempts: 3 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: streamlitprueba
      password: prueba # Will be hashed automatically
cookie:
  expiry_days: 0
  key: "robertokey" # Must be string
  name: cookieappstl
pre-authorized:
  emails:
  - melsby@gmail.com